### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by zachshallbetter**
Significant adjustments

### CODE REVIEW

**Comment by vasilecampeanu** [comment]
Hello, thank you for the pull request. Is there a reason why you closed it?

**Comment by vasilecampeanu** [comment]
Hello, thank you for the pull request. Is there a reason why you closed it?

**Comment by zachshallbetter** [comment]
Hey! It was premature (and very broken). I was attempting to make the pull request to test a CI within my fork. Also, I still needed to squash my commits, so it was sloppy. I'll have a new version here shortly.

I'm also working on refactoring the SSE Service and OpenAI API. Those are close to complete as well.
I have a preliminary enhancement for tokenization and embeddings, which we can look at if/when you approve the API refactor.

**Comment by vasilecampeanu** [comment]
Sure, any help is appreciated. Please take a look at the most recent commit I've made. I've added visibility control for different parts of a message. This addition was necessary for providing more context to GPT-3.5. There were instances where it was unsure how to proceed with the selected text sent by the user to the chat since it wasn't specified in the respective assistant message.

**Comment by zachshallbetter** [comment]
That makes sense. I'll give it a review. Feel free to take a look through my repositories I have some significant adjustments in the pipe. 

- I'm fairly close to tuning your dev branch. [develop](https://github.com/zachshallbetter/obsidian-weaver/tree/develop)
- SSE Merge is a rebuild of the API. I removed several dependencies (SSE among them) [sse-merge](https://github.com/zachshallbetter/obsidian-weaver/tree/sse-merge).
- Refactor contains the previous three but includes a node compiler, among other changes. [refactor](https://github.com/zachshallbetter/obsidian-weaver/tree/refactor)


After these items, tokenization might be a relatively quick way to solve some message size concerns. Here's my list for that, context, embedding, etc:

### **Weaver Plugin Enhanced Features for Conversations and Threads**:

### **1. Efficient Tokenization with Tiktoken**:
- **Quick Setup**: Easily integrate Tiktoken into Weaver.
- **Content Tokenization**: Convert note contents into manageable tokens for analysis.

### **2. Advanced Embedding Generation with OpenAI**:
- **Seamless Integration**: Utilize OpenAI directly from Weaver.
- **Embedding Creation**: Convert conversations into embeddings, enhancing chat experiences.

### **3. Streamlined Tokens & Embeddings Storage**:
- **Organized Storage**: Use Obsidian's tools to store tokens and embeddings neatly.
- **Easy Access**: Quickly retrieve and manage saved data with Obsidian's methods.

### **4. Context Menu Enhancements**:
- **Extended Options**: Expand the context menu with Weaver's features.
- **Intuitive Interactions**: Directly access Weaver functionalities like tokenization from the menu.

### **5. Comprehensive Embedding Catalogue**:
- **Organized List**: Maintain a clear catalog of all available embeddings.
- **User-friendly Management**: Easily add, modify, or remove embeddings.

### **6. User-friendly Interface Design**:
- **Embedding Selection**: Pick embeddings with a simple dropdown or list.
- **Visual Feedback**: See real-time effects or descriptions of selected embeddings.

### **7. Dynamic Embedding Application**:
- **Easy Apply**: Use selected embeddings in conversations effortlessly.
- **Consistent Experience**: Ensure embeddings shape conversations as intended.

### **8. Customizable Storage & Retrieval**:
- **Folder Organization**: Categorize and store conversations in custom folders.
- **Fast Search**: Locate conversations quickly based on criteria.
- **Flexible Sorting**: Arrange conversations by date, relevance, or custom parameters.

### **9. User-Powered Customization**:
- **Add Custom Embeddings**: Introduce a personal touch by adding custom embeddings.
- **Safe and Compatible**: Ensure user-added embeddings work seamlessly.

### **10. Intelligent Conversation Analysis**:
- **Deep Dive into Structure**: Understand the layout of conversations for better insights.
- **Enhanced Analysis**: Apply NLP techniques for sentiment and frequency insights.

**Comment by vasilecampeanu** [comment]
This looks really good. When I started this project, I was pretty new to TypeScript and React, so the code got a bit messy. I had all these improvements in mind but couldn't find the time to sort them out.

**Comment by zachshallbetter** [comment]
My pleasure. 

Your code was great, honestly. There are minimal obvious “code” items I needed to change. Your interface was clean and conceptually well thought-out.

I’ve been using Gitbook forever and just moved to Obsidian a few days ago. Frankly, your plug-in and the environment are why I decided to stay and migrate my docs. 

Now, the big item for me are - the ones I listed earlier. Embedding documentation into conversations without input (which you’ve done a lot of. Grammarly like, AI content editing and generation, and improving the markdown and markdown code locks in the chat and editor.

Also, I reduced the reliance on dependencies and config across the board (lodash, BSON, SSE, esBuild) and refactored their functionality into the code or build process. So, of it seems like I dramatically changed the structure, that's what you're seeing. 

Also, a nice “bonus” is that I was able to add independent hot-reload. So, when saving during dev, it’ll reload the interface without needing another plugin e.g. “.hotreload”.  That should make the dev process a little easier. It will also increment the version in package.json and generate the git tag (after comparison) on release.

If you’re interested, we should move our conversation somewhere else.

**Comment by vasilecampeanu** [comment]
Yes, we could continue our discussion on Discord (username: vasilecampeanu), if you'd like.

Here are some additional features that I'm thinking about:

### 1. Related Conversations
This feature would introduce an indicator for each note that has 'linked' conversations. For instance, if I choose to use a note as context for a chat, or select text from a note and send it to the chat, a visual indication would be shown, similar to what can be seen in the 'Strange New Worlds' plugin.

Screenshot 2023-07-31 at 22 16 18

I think this would make the assistant much more useful.

### 2. Title Generation
There should be an option for generating titles in the same way that ChatGPT does.

### 4. Suggestions
Like BingChat, which offers summaries of web pages when you open them.

### 5. Support for Other Models from OpenAI
I am particularly interested in adding support for DALL-E.

### 6. Adding Support for Non-OpenAI LLMs
This could be advantageous for those who want to run LLaMA or other models locally.

### 7. Web Browsing
This feature would introduce the ability to search the internet, much like the web browser plugin from GPT-4 or BingChat. I currently have no idea about how this could be implemented, but I plan to research it further.

### 8. Token Management
We should add a graph view so users can see exactly how much they've spent directly from Obsidian without needing to visit OpenAI's website.

**Pull request closed without merging**
